[repository]
name = "hyprexpo"
authors = ["Vaxry && GodKeawa"]

commit_pins = [
    ["af923e30d1d24f1f4a4f5cb8308065173c1d9539", "1ca6f758f637e648fb3bf498d7cf9818eb88473a"],  # 0.55.0
    ["a47147bc095e5b3be3eb8bd04f0ac242b968cd4d", "42640b0c5ca0d61e3251f26f7e9f0eb710cc7ea2"],  # 0.55.1
]

[hyprexpo]
description = "hyprexpo — niri like scroll expo plugin for Hyprland"
authors = ["Vaxry && GodKeawa"]
output = "hyprexpo.so"
build = [
    "make all"
]

since_hyprland = 6066