[repository]
name = "hyprexpo"
authors = ["GodKeawa"]

[hyprexpo]
description = "hyprexpo — niri scroll expo plugin for Hyprland"
authors = ["GodKeawa"]
output = "hyprexpo.so"
build = [
    "make all"
]

since_hyprland = 6066